# Generated by Django 3.0.6 on 2020-05-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AsanaUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AsanaTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asana_models.AsanaProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asana_models.AsanaUser')),
            ],
        ),
    ]
